Repository kralsito/Proyecto-Agiles, pull requests merged in 2023-10, with the labels that each got.

#36 Feature: Modal para Registro
  back/proyecto_perros/media/perros/belgrano_bandera.jpg
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
Labels: bug, enhancement, feature

#37 Enhancement: Mejoras en el estilo
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/footer/footer.component.css
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/login/login.component.css
  front/front_perros/src/app/login/login.component.html
  front/front_perros/src/app/menu-principal/menu-principal.component.css
  front/front_perros/src/app/menu-principal/menu-principal.component.html
  front/front_perros/src/app/nav-bar/nav-bar.component.css
  front/front_perros/src/app/nav-bar/nav-bar.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.css
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.html
  front/front_perros/src/assets/img/back.png
  front/front_perros/src/assets/img/back2.png
  front/front_perros/src/assets/img/index-foto (1).png
  front/front_perros/src/assets/img/index-foto.png
  front/front_perros/src/styles.css
Labels: enhancement

#38 Feature: botones de volver a inicio en los forms
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
Labels: enhancement, feature

#39 Feature/conexion log
  README.md
  back/proyecto_perros/pagina_perros/admin.py
  back/proyecto_perros/pagina_perros/migrations/0001_initial.py
  back/proyecto_perros/pagina_perros/migrations/0002_alter_publicacion_sexoperro.py
  back/proyecto_perros/pagina_perros/migrations/0003_alter_publicacion_sexoperro.py
  back/proyecto_perros/pagina_perros/migrations/0004_alter_publicacion_sexoperro.py
  back/proyecto_perros/pagina_perros/migrations/0005_customuser.py
  back/proyecto_perros/pagina_perros/migrations/0006_usuario_delete_customuser.py
  back/proyecto_perros/pagina_perros/migrations/0007_remove_usuario_contraseña_alter_usuario_password.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
  back/proyecto_perros/proyecto_perros/settings.py
  back/proyecto_perros/proyecto_perros/urls.py
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/login/login.component.ts
  front/front_perros/src/app/login/login.service.spec.ts
  front/front_perros/src/app/login/login.service.ts
  front/front_perros/src/app/usuario.model.ts
Labels: feature

#41 Feature: Mensaje de correo electrónico ya registrado
  back/proyecto_perros/pagina_perros/models.py
  front/front_perros/src/app/alert-mail-duplicado/alert-mail-duplicado.component.css
  front/front_perros/src/app/alert-mail-duplicado/alert-mail-duplicado.component.html
  front/front_perros/src/app/alert-mail-duplicado/alert-mail-duplicado.component.spec.ts
  front/front_perros/src/app/alert-mail-duplicado/alert-mail-duplicado.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/styles.css
Labels: feature

#42 Refactor: Registro
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/formusuario/formusuario.component.ts
Labels: bug, enhancement

#45 Refactor: Registro v2
  front/front_perros/angular.json
  front/front_perros/package-lock.json
  front/front_perros/package.json
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/styles.css
Labels: bug, documentation

#46 Feature: Función y modal para cerrar sesión
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.component.css
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.component.html
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.component.spec.ts
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.component.ts
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.service.spec.ts
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.service.ts
  front/front_perros/src/app/nav-bar/nav-bar.component.css
  front/front_perros/src/app/nav-bar/nav-bar.component.html
  front/front_perros/src/app/nav-bar/nav-bar.component.ts
Labels: feature

#47 Feature: Nav-bar para usuarios logueados y no logueados
  front/front_perros/package-lock.json
  front/front_perros/package.json
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.component.css
  front/front_perros/src/app/dialog-cerrar-sesion/dialog-cerrar-sesion.service.ts
  front/front_perros/src/app/login/login.component.ts
  front/front_perros/src/app/login/login.service.ts
  front/front_perros/src/app/nav-bar/nav-bar.component.css
  front/front_perros/src/app/nav-bar/nav-bar.component.html
Labels: feature

#48 Feature: Guardián de acceso a la página
  README.md
  front/front_perros/package-lock.json
  front/front_perros/package.json
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/guards/auth.guard.spec.ts
  front/front_perros/src/app/guards/auth.guard.ts
  front/front_perros/src/app/guards/auth.service.spec.ts
  front/front_perros/src/app/guards/auth.service.ts
Labels: feature

#49 Feature: Pagina de Perfil
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/perfil/perfil.component.css
  front/front_perros/src/app/perfil/perfil.component.html
  front/front_perros/src/app/perfil/perfil.component.spec.ts
  front/front_perros/src/app/perfil/perfil.component.ts
Labels: enhancement

#50 feature: Publicacion y usuarios
  back/proyecto_perros/media/perros/OIP_1_nL97KPJ.jpg
  back/proyecto_perros/media/perros/OIP_E5HvGHa.jpg
  back/proyecto_perros/pagina_perros/migrations/0001_initial.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/src/app/guards/auth.service.ts
  front/front_perros/src/app/perro.model.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
Labels: feature

#51 enhancement: El formulario registro ya no envia el nombre del usuario
  back/proyecto_perros/pagina_perros/migrations/0002_remove_user_name.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
Labels: enhancement

#52 feature: Modelo de perfil para un usuario
  back/proyecto_perros/pagina_perros/admin.py
  back/proyecto_perros/pagina_perros/migrations/0003_perfil.py
  back/proyecto_perros/pagina_perros/models.py
Labels: feature

#53 Feature: Filtros para las publicaciones
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.ts
Labels: feature

#55 Feature: Modal para Me Interesa
  front/front_perros/package-lock.json
  front/front_perros/package.json
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.ts
Labels: enhancement, feature

#56 feature: url para ver mi perfil
  back/proyecto_perros/pagina_perros/urls.py
Labels: feature

#57 feature: endpoint para poder dar de alta un perfil
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
Labels: feature

#58 fix: ya no se muestra el id del usuario, ahora se muestra el mail
  back/proyecto_perros/media/perros/7ede7def-c10f-4d81-9cda-cb1879963fd6.jpg
  back/proyecto_perros/media/perros/82816632b33390ef95debd594b8706ec.jpg
  back/proyecto_perros/media/perros/Sin_títuloAAAA.png
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.ts
Labels: fix

#60 Feature: Link entre Usuario y Perfil y otras cosas
  back/proyecto_perros/media/perros/belgrano_bandera_W988KQI.jpg
  back/proyecto_perros/media/perros/daa6b25f3b041c1ff6f6f9283e6ee58c_ab2oY2J.jpg
  back/proyecto_perros/media/perros/descarga.jpeg
  back/proyecto_perros/pagina_perros/migrations/0004_remove_perfil_descripcion_remove_perfil_fotoperfil.py
  back/proyecto_perros/pagina_perros/migrations/0005_alter_perfil_usuario.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/src/app/alerts/alert-credenciales-invalidas/alert-credenciales-invalidas.component.css
  front/front_perros/src/app/alerts/alert-credenciales-invalidas/alert-credenciales-invalidas.component.html
  front/front_perros/src/app/alerts/alert-credenciales-invalidas/alert-credenciales-invalidas.component.spec.ts
  front/front_perros/src/app/alerts/alert-credenciales-invalidas/alert-credenciales-invalidas.component.ts
  front/front_perros/src/app/alerts/alert-mail-duplicado/alert-mail-duplicado.component.css
  front/front_perros/src/app/alerts/alert-mail-duplicado/alert-mail-duplicado.component.html
  front/front_perros/src/app/alerts/alert-mail-duplicado/alert-mail-duplicado.component.spec.ts
  front/front_perros/src/app/alerts/alert-mail-duplicado/alert-mail-duplicado.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/login/login.component.ts
  front/front_perros/src/app/nav-bar/nav-bar.component.html
  front/front_perros/src/app/perfil.model.ts
  front/front_perros/src/app/perfil/formperfil.service.spec.ts
  front/front_perros/src/app/perfil/formperfil.service.ts
  front/front_perros/src/app/usuario.model.ts
Labels: enhancement, Back, Front, feature

#61 Feature: Mi Perfil
  back/proyecto_perros/media/perros/belgrano_bandera_F5oSUYF.jpg
  back/proyecto_perros/media/perros/daa6b25f3b041c1ff6f6f9283e6ee58c_MHtlvVp.jpg
  back/proyecto_perros/media/perros/daa6b25f3b041c1ff6f6f9283e6ee58c_lTvgAnY.jpg
  back/proyecto_perros/media/perros/descarga_BU6FAKH.jpeg
  back/proyecto_perros/media/perros/descarga_rL0Iwaq.jpeg
  back/proyecto_perros/pagina_perros/migrations/0006_remove_perfil_usuario_remove_publicacion_usuario_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0007_publicacion_usuario.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/package-lock.json
  front/front_perros/package.json
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/guards/auth.service.ts
  front/front_perros/src/app/perfil/perfil.component.html
  front/front_perros/src/app/perfil/perfil.component.ts
  front/front_perros/src/app/perfil/service-retrieve/retrieve.service.spec.ts
  front/front_perros/src/app/perfil/service-retrieve/retrieve.service.ts
Labels: enhancement, Back, Front, feature

#62 Enhancement: Atributos Publicacion/Perro
  back/proyecto_perros/pagina_perros/migrations/0008_publicacion_castradoperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0009_alter_publicacion_castradoperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0010_alter_publicacion_castradoperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0011_alter_publicacion_castradoperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0012_alter_publicacion_castradoperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0013_publicacion_vacunadoperro.py
  back/proyecto_perros/pagina_perros/models.py
  front/front_perros/src/app/perro.model.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/favicon.ico
Labels: enhancement, Back, Front

#63 Enhancement: Se añadieron más filtros para las publicaciones
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.ts
Labels: enhancement

#64 Feature: Se añadió un guard para usuarios logeados
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/guards/sesion-guard.guard.spec.ts
  front/front_perros/src/app/guards/sesion-guard.guard.ts
Labels: feature

#71 Feature: Función para editar una publicación
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/mis-publicaciones/mis-publicaciones.component.css
  front/front_perros/src/app/mis-publicaciones/mis-publicaciones.component.html
  front/front_perros/src/app/mis-publicaciones/mis-publicaciones.component.ts
  front/front_perros/src/app/mis-publicaciones/mis-publicaciones.service.ts
Labels: feature
