Repository kralsito/Proyecto-Agiles, pull requests merged in 2023-09, with the labels that each got.

#1 Feature: Endpoint para dar de alta una publicacion
  back/proyecto_perros/.gitignore
  back/proyecto_perros/media/perros/OIP.jpg
  back/proyecto_perros/media/perros/OIP_1.jpg
  back/proyecto_perros/pagina_perros/admin.py
  back/proyecto_perros/pagina_perros/migrations/0001_initial.py
  back/proyecto_perros/pagina_perros/migrations/0002_publicacion_fotoperro_publicacion_imagenperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0003_remove_publicacion_imagenperro.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
  back/proyecto_perros/proyecto_perros/settings.py
  back/proyecto_perros/proyecto_perros/urls.py
Labels: enhancement

#2 Feature/ver publicacion back
  back/proyecto_perros/media/perros/OIP_1_MGp9l3T.jpg
  back/proyecto_perros/pagina_perros/migrations/0004_alter_publicacion_fotoperro.py
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
  back/proyecto_perros/proyecto_perros/settings.py
Labels: enhancement

#8 Feature: botón para poder navegar de app.component a publicacion.component
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/publicacion/publicacion.component.ts
Labels: good first issue

#10 Fixes y creacion de componente perros
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/perro/perro.component.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.spec.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
  front/front_perros/src/app/perros/perro/perro.component.css
  front/front_perros/src/app/perros/perro/perro.component.html
  front/front_perros/src/app/perros/perro/perro.component.spec.ts
  front/front_perros/src/app/perros/perro/perro.component.ts
  front/front_perros/src/app/perros/perros.component.css
  front/front_perros/src/app/perros/perros.component.html
  front/front_perros/src/app/perros/perros.component.spec.ts
  front/front_perros/src/app/perros/perros.component.ts
Labels: enhancement

#13 Correccion de errores y separacion de ambientes v2
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/perro.model.ts
  front/front_perros/src/app/perros.service.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/perro/perro.component.html
  front/front_perros/src/app/perros/perros.component.html
Labels: bug, enhancement, good first issue

#15 Enhancement: Estilos CSS para el formulario de altaPublicacion()
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
Labels: enhancement

#18 Modificacion en el readme y en el formulario
  README.md
  back/proyecto_perros/media/perros/Captura_de_pantalla_2023-05-26_155516.png
  back/proyecto_perros/media/perros/OIP.jpg
  back/proyecto_perros/media/perros/OIP_1.jpg
  back/proyecto_perros/media/perros/OIP_1_DgXPzAv.jpg
  back/proyecto_perros/media/perros/OIP_1_MGp9l3T.jpg
  back/proyecto_perros/media/perros/OIP_1_mOPA2dl.jpg
  back/proyecto_perros/media/perros/OIP_TzPAU17.jpg
  back/proyecto_perros/media/perros/a28aec0e-8462-41de-a905-5da222960a4e.jpg
  back/proyecto_perros/media/perros/jose-de-san-martin_1440x810_wmk.jpg
  back/proyecto_perros/pagina_perros/migrations/0001_initial.py
  back/proyecto_perros/pagina_perros/migrations/0002_publicacion_fotoperro_publicacion_imagenperro_and_more.py
  back/proyecto_perros/pagina_perros/migrations/0003_remove_publicacion_imagenperro.py
  back/proyecto_perros/pagina_perros/migrations/0004_alter_publicacion_fotoperro.py
  back/proyecto_perros/pagina_perros/migrations/0005_rename_tamañoperro_publicacion_tamanioperro.py
  back/proyecto_perros/pagina_perros/migrations/0006_alter_publicacion_sexoperro.py
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
Labels: documentation

#17 Feature: Creacion e implementacion de servicio Home
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/home.service.spec.ts
  front/front_perros/src/app/home.service.ts
Labels: enhancement

#19 Feature: Creación del componente Footer.
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/footer/footer.component.css
  front/front_perros/src/app/footer/footer.component.html
  front/front_perros/src/app/footer/footer.component.spec.ts
  front/front_perros/src/app/footer/footer.component.ts
Labels: enhancement

#23 feature: Modificacion en el modelo publicacion
  back/proyecto_perros/media/perros/Captura_de_pantalla_2023-05-26_155516.png
  back/proyecto_perros/media/perros/OIP.jpg
  back/proyecto_perros/media/perros/OIP_1.jpg
  back/proyecto_perros/media/perros/OIP_1_OtRQahg.jpg
  back/proyecto_perros/pagina_perros/migrations/0002_alter_publicacion_sexoperro.py
  back/proyecto_perros/pagina_perros/migrations/0003_alter_publicacion_sexoperro.py
  back/proyecto_perros/pagina_perros/models.py
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
Labels: enhancement

#24 Enhancement: Mejoras en el front del menú
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/nav-bar/nav-bar.component.css
  front/front_perros/src/app/nav-bar/nav-bar.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.css
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.html
Labels: enhancement

#26 Feature: Crear Usuario (front)
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/formusuario/formuser.service.spec.ts
  front/front_perros/src/app/formusuario/formuser.service.ts
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/formusuario/formusuario.component.spec.ts
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/usuario.model.ts
Labels: enhancement, good first issue, feature

#27 Feature/conexion reg
  back/proyecto_perros/pagina_perros/admin.py
  back/proyecto_perros/pagina_perros/migrations/0007_remove_usuario_contraseña_alter_usuario_password.py
  back/proyecto_perros/pagina_perros/models.py
  back/proyecto_perros/pagina_perros/serializers.py
  back/proyecto_perros/pagina_perros/views.py
  front/front_perros/src/app/formusuario/formuser.service.ts
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/formusuario/formusuario.component.ts
  front/front_perros/src/app/usuario.model.ts
Labels: enhancement

#29 Enhancement: Visualización del input file en formpublicacion"
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
Labels: enhancement

#30 Feature: Login y algunos fixes
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/home.service.ts
  front/front_perros/src/app/login/login.component.css
  front/front_perros/src/app/login/login.component.html
  front/front_perros/src/app/login/login.component.spec.ts
  front/front_perros/src/app/login/login.component.ts
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.css
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.html
Labels: enhancement

#32 Feature: Modal para publicación publicada
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.css
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.html
  front/front_perros/src/app/perros/formpublicacion/formpublicacion.component.ts
Labels: enhancement, feature

#33 Enhancement: Boton de User para registro
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/nav-bar/nav-bar.component.css
  front/front_perros/src/app/nav-bar/nav-bar.component.html
Labels: enhancement

#34 Enhancement: Routing y Estilos
  back/proyecto_perros/media/perros/Flag_of_Lebanon_tree.png
  back/proyecto_perros/media/perros/WhatsApp_Image_2023-07-17_at_23.16.32.jpeg
  back/proyecto_perros/media/perros/daa6b25f3b041c1ff6f6f9283e6ee58c.jpg
  front/front_perros/src/app/app-routing.module.ts
  front/front_perros/src/app/app.component.css
  front/front_perros/src/app/app.component.html
  front/front_perros/src/app/app.component.ts
  front/front_perros/src/app/app.module.ts
  front/front_perros/src/app/footer/footer.component.css
  front/front_perros/src/app/formusuario/formusuario.component.css
  front/front_perros/src/app/formusuario/formusuario.component.html
  front/front_perros/src/app/home.service.spec.ts
  front/front_perros/src/app/home.service.ts
  front/front_perros/src/app/login/login.component.css
  front/front_perros/src/app/login/login.component.html
  front/front_perros/src/app/menu-principal/menu-principal.component.css
  front/front_perros/src/app/menu-principal/menu-principal.component.html
  front/front_perros/src/app/publicacion/publicacion.component.css
  front/front_perros/src/app/publicacion/publicacion.component.html
  front/front_perros/src/app/titulo-yeslogan/titulo-yeslogan.component.css
  front/front_perros/src/index.html
Labels: bug, enhancement

#35 Feature/login back
  back/proyecto_perros/pagina_perros/urls.py
  back/proyecto_perros/pagina_perros/views.py
  back/proyecto_perros/proyecto_perros/settings.py
Labels: feature
